manifest:
    remotes:
      - name: seenemikk
        url-base: https://github.com/seenemikk
      - name: ncs
        url-base: https://github.com/nrfconnect
      - name: nordicsemi
        url-base: https://github.com/NordicSemiconductor
      - name: zephyr
        url-base: https://github.com/zephyrproject-rtos

    defaults:
        remote: seenemikk

    projects:
      - name: nrf
        repo-path: sdk-nrf
        revision: v2.0.2-smartwatch
      - name: zephyr
        repo-path: sdk-zephyr
        revision: v3.0.99-ncs1-smartwatch
        import:
            name-allowlist:
              - cmsis
              - hal_nordic
              - segger
      - name: mcuboot
        repo-path: sdk-mcuboot
        revision: v1.9.99-ncs1
        path: bootloader/mcuboot
      - name: mbedtls-nrf
        repo-path: sdk-mbedtls
        revision: v3.0.0-ncs2
        path: mbedtls
      - name: nrfxlib
        repo-path: sdk-nrfxlib
        revision: v2.0.2
        path: nrfxlib
      - name: lvgl
        revision: af95bdfcf6784edd958ea08139c713e2d3dee7af
        path: modules/lib/gui/lvgl
      - name: tinycrypt
        revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
        path: modules/crypto/tinycrypt
        remote: zephyr
      - name: zcbor
        remote: nordicsemi
        revision: 3d36ae19cb05d28cea23b4c870ae965c44215e9c
        path: modules/lib/zcbor

    self:
        path: application
